### ISSUE TITLE
Error: utils.status.show() "text" property must be a non-empty string

### ISSUE THREAD

**Issue by nhoizey** [borisschapira/netlify-build-plugin-dareboost#3]
I added the plugin to the build for https://nicolas-hoizey-com.netlify.app/ based on https://github.com/nhoizey/nicolas-hoizey.com/ and I get this error:

```
Plugin "netlify-build-plugin-dareboost" internal error
Error: utils.status.show() "text" property must be a non-empty string
In "onSuccess" event in "netlify-build-plugin-dareboost" from netlify.toml and package.json at onSuccess (/node_modules/netlify-build-plugin-dareboost/index.js:107:5)
```

![image](https://user-images.githubusercontent.com/78213/84300930-3f3fc300-ab53-11ea-9e02-2e60d2d5074a.png)

The event has however been added to my [4 reports](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/netlify.toml#L19):

![image](https://user-images.githubusercontent.com/78213/84301087-8a59d600-ab53-11ea-8bbb-13507a3a0a4c.png)

**Comment by borisschapira** [comment]
Thanks @nhoizey, it's fixed and merged into Netlify's native plugin list.

**Comment by nhoizey** [comment]
You're welcome, thanks for the quick fix! 👍
